# Generated by Django 4.0.5 on 2022-08-23 16:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments_To_Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='New Forum', max_length=150)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 16, 10, 45, 431275))),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 16, 10, 45, 430543)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 16, 10, 45, 431092)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 23, 16, 10, 45, 430905)),
        ),
        migrations.CreateModel(
            name='Replies_To_Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 8, 23, 16, 10, 45, 431465))),
                ('description', models.TextField()),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.comments_to_forum')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comments_to_forum',
            name='forum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='back_app.forum'),
        ),
        migrations.AddField(
            model_name='comments_to_forum',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
