# Generated by Django 4.0.5 on 2022-08-24 00:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 0, 20, 6, 481436)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 0, 20, 6, 482945)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 0, 20, 6, 482296)),
        ),
    ]
