# Generated by Django 4.0.5 on 2022-08-29 00:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_completed',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 38, 21, 678101)),
        ),
        migrations.AlterField(
            model_name='comments_to_post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 38, 21, 678745)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 38, 21, 678366)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 38, 21, 678574)),
        ),
        migrations.AlterField(
            model_name='replies_to_comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 29, 0, 38, 21, 678912)),
        ),
    ]
