# Generated by Django 4.0.5 on 2022-08-24 02:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0002_alter_appliedjobs_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 27, 33, 125244)),
        ),
        migrations.AlterField(
            model_name='comments_to_post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 27, 33, 127518)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 27, 33, 126034)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 27, 33, 126571)),
        ),
        migrations.AlterField(
            model_name='replies_to_comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 24, 2, 27, 33, 128156)),
        ),
    ]
