# Generated by Django 4.0.5 on 2022-08-20 00:47

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0002_appuser_job_title_appuser_profile_picture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='name',
        ),
        migrations.AddField(
            model_name='appuser',
            name='fist_name',
            field=models.CharField(default='unkown', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='job_title',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='last_name',
            field=models.CharField(default='unknown', max_length=50),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='profile_picture',
            field=models.CharField(default='https://icon-library.com/images/default-profile-icon/default-profile-icon-24.jpg', max_length=250),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateTimeField(default=datetime.datetime(2022, 8, 20, 0, 47, 8, 722711))),
                ('completed', models.BooleanField(default=False)),
                ('company_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Forum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 8, 20, 0, 47, 8, 722850))),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AppliedJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(default=datetime.datetime(2022, 8, 20, 0, 47, 8, 722505))),
                ('date_completed', models.DateField(null=True)),
                ('deadline', models.DateField(null=True)),
                ('company_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('company_link', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
