# Generated by Django 4.0.5 on 2022-08-20 00:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0003_remove_appuser_name_appuser_fist_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(default='New Forum', max_length=150),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 0, 54, 33, 274467)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 0, 54, 33, 274871)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 0, 54, 33, 274710)),
        ),
    ]
