# Generated by Django 4.0.5 on 2022-08-28 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0003_alter_appliedjobs_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='first_name',
            field=models.CharField(default='first_name', max_length=150),
        ),
        migrations.AddField(
            model_name='posts',
            name='last_name',
            field=models.CharField(default='last_name', max_length=150),
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 55, 53, 207798)),
        ),
        migrations.AlterField(
            model_name='comments_to_post',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 55, 53, 210137)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 55, 53, 208797)),
        ),
        migrations.AlterField(
            model_name='posts',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 55, 53, 209432)),
        ),
        migrations.AlterField(
            model_name='replies_to_comment',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 28, 14, 55, 53, 210749)),
        ),
    ]
