# Generated by Django 4.0.5 on 2022-08-20 02:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0004_forum_title_alter_appliedjobs_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 2, 0, 22, 779632)),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 2, 0, 22, 779985)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 20, 2, 0, 22, 779838)),
        ),
    ]
