# Generated by Django 4.0.5 on 2022-08-21 05:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back_app', '0006_alter_appliedjobs_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appuser',
            name='fist_name',
        ),
        migrations.AlterField(
            model_name='appliedjobs',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 5, 57, 54, 741297)),
        ),
        migrations.AlterField(
            model_name='appuser',
            name='first_name',
            field=models.CharField(default='unkown', max_length=50),
        ),
        migrations.AlterField(
            model_name='forum',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 5, 57, 54, 741651)),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 5, 57, 54, 741505)),
        ),
    ]
